/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as ListingsIndexRouteImport } from './routes/listings.index'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as RentalsIndexRouteImport } from './routes/rentals.index'
import { Route as RentalsIdRouteImport } from './routes/rentals.$id'
import { Route as SavedIndexRouteImport } from './routes/saved.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIndexRoute = ListingsIndexRouteImport.update({
  id: '/listings/',
  path: '/listings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsIndexRoute = RentalsIndexRouteImport.update({
  id: '/rentals/',
  path: '/rentals/',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsIdRoute = RentalsIdRouteImport.update({
  id: '/rentals/$id',
  path: '/rentals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedIndexRoute = SavedIndexRouteImport.update({
  id: '/saved/',
  path: '/saved/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/listings/$id': typeof ListingsIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/rentals/$id': typeof RentalsIdRoute
  '/insights/': typeof InsightsIndexRoute
  '/listings/': typeof ListingsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/rentals/': typeof RentalsIndexRoute
  '/saved/': typeof SavedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/listings/$id': typeof ListingsIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/rentals/$id': typeof RentalsIdRoute
  '/insights': typeof InsightsIndexRoute
  '/listings': typeof ListingsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/rentals': typeof RentalsIndexRoute
  '/saved': typeof SavedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/listings/$id': typeof ListingsIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/rentals/$id': typeof RentalsIdRoute
  '/insights/': typeof InsightsIndexRoute
  '/listings/': typeof ListingsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/rentals/': typeof RentalsIndexRoute
  '/saved/': typeof SavedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/listings/$id'
    | '/projects/$id'
    | '/rentals/$id'
    | '/insights/'
    | '/listings/'
    | '/projects/'
    | '/rentals/'
    | '/saved/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/listings/$id'
    | '/projects/$id'
    | '/rentals/$id'
    | '/insights'
    | '/listings'
    | '/projects'
    | '/rentals'
    | '/saved'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/listings/$id'
    | '/projects/$id'
    | '/rentals/$id'
    | '/insights/'
    | '/listings/'
    | '/projects/'
    | '/rentals/'
    | '/saved/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ListingsIdRoute: typeof ListingsIdRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  RentalsIdRoute: typeof RentalsIdRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  ListingsIndexRoute: typeof ListingsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  RentalsIndexRoute: typeof RentalsIndexRoute
  SavedIndexRoute: typeof SavedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/': {
      id: '/listings/'
      path: '/listings'
      fullPath: '/listings/'
      preLoaderRoute: typeof ListingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals/': {
      id: '/rentals/'
      path: '/rentals'
      fullPath: '/rentals/'
      preLoaderRoute: typeof RentalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals/$id': {
      id: '/rentals/$id'
      path: '/rentals/$id'
      fullPath: '/rentals/$id'
      preLoaderRoute: typeof RentalsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved/': {
      id: '/saved/'
      path: '/saved'
      fullPath: '/saved/'
      preLoaderRoute: typeof SavedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ListingsIdRoute: ListingsIdRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  RentalsIdRoute: RentalsIdRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  ListingsIndexRoute: ListingsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  RentalsIndexRoute: RentalsIndexRoute,
  SavedIndexRoute: SavedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
